@baseUr = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}

# @name create_acount
POST {{baseUr}}/accounts
Content-Type: application/json

{
  "name":"testee",
  "email":"email3@email.com",
  "document":"document",
  "password":"1234567"
}

###
# @name authenticate

POST {{baseUr}}/sessions
Content-Type: application/json

{
  "email":"email3@email.com",
  "password":"1234567"
}

###
# @name whats-app

POST {{baseUr}}/whats-app
Content-Type: application/json
