services:
  postgres:
    container_name: scheduler-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
